// Original file name: MemoCalc.h
// Generated by piBuilder @ 22/10/2003 15:45:17

#define EditView 1
#define VarsField 2
#define ExprField 3
#define EvalButton 4
#define ResultField 5
#define ListView 6
#define NewButton 8
#define MemoCalc 9
#define AppVersion 10
#define ExprTable 11
#define UpButton 12
#define DownButton 13
#define DoneButton 14
#define ListViewMenu 15
#define EditViewMenu 16
#define Pulldown17 17
#define ListViewRecordNewMenu 18
#define ListViewRecordDeleteMenu 19
#define Pulldown20 20
#define ListViewOptionsAboutMenu 21
#define Pulldown22 22
#define EditViewEditCutMenu 23
#define EditViewEditCopyMenu 24
#define EditViewEditPasteMenu 25
#define Pulldown26 26
#define EditViewOptionsAboutMenu 27
#define AboutDialog 28
#define MemoCalc01bpp 29
#define AboutLabel 30
#define AboutOkButton 31
#define MemoCalcHelpString 32
